server:
  port: 9002
spring:
  application:
    name: node2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true